//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendance.WebForms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQL5088.site4now.net;Initial Catalog=db_a8935f_slr;User Id=db_a8935f_" +
            "slr_admin;Password=0925Greg#")]
        public string SQLCon {
            get {
                return ((string)(this["SQLCon"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQL5088.site4now.net;Initial Catalog=db_a8935f_slr;User Id=db_a8935f_" +
            "slr_admin;Password=0925Greg#")]
        public string SQLBackup1 {
            get {
                return ((string)(this["SQLBackup1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ICONNECTIVITY\\SQLEXPRESS;Initial Catalog=SOHdb;Integrated Security=Tr" +
            "ue")]
        public string SQLBackup2 {
            get {
                return ((string)(this["SQLBackup2"]));
            }
        }
    }
}
