//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendance.WebForms
{
    public partial class AdminPanel
    {
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.LinkButton btnDashboard;
        protected global::System.Web.UI.WebControls.LinkButton btnAdminPanel;
        protected global::System.Web.UI.WebControls.Label lblTotalUsers;
        protected global::System.Web.UI.WebControls.Label lblActiveEmployees;
        protected global::System.Web.UI.WebControls.Label lblDepartments;
        protected global::System.Web.UI.WebControls.Label lblUptime;
        protected global::System.Web.UI.WebControls.HyperLink hlkSettings;
        protected global::System.Web.UI.WebControls.HyperLink hlkUserManagement;
        protected global::System.Web.UI.WebControls.HyperLink hlkAuditTrail;
        protected global::System.Web.UI.WebControls.HyperLink hlkCompliance;
        protected global::System.Web.UI.WebControls.HyperLink hlkDataAccess;
        protected global::System.Web.UI.WebControls.HyperLink hlkReports;
        protected global::System.Web.UI.WebControls.TextBox txtHolidayName;
        protected global::System.Web.UI.WebControls.TextBox txtHolidayDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlHolidayType;
        protected global::System.Web.UI.WebControls.Button btnAddHoliday;
        protected global::System.Web.UI.WebControls.GridView gvHolidays;
        protected global::System.Web.UI.WebControls.Button btnRunMaintenance;
    }
}
