//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendance.WebForms
{
    public partial class DataAccessLog
    {
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.LinkButton btnAuditTrail;
        protected global::System.Web.UI.WebControls.LinkButton btnComplianceStatus;
        protected global::System.Web.UI.WebControls.LinkButton btnDataAccess;
        protected global::System.Web.UI.WebControls.LinkButton btnViolations;
        protected global::System.Web.UI.WebControls.LinkButton btnReports;
        protected global::System.Web.UI.WebControls.Label lblTotalAccess;
        protected global::System.Web.UI.WebControls.Label lblExports;
        protected global::System.Web.UI.WebControls.Label lblSensitiveAccess;
        protected global::System.Web.UI.WebControls.Label lblUnauthorized;
        protected global::System.Web.UI.WebControls.DropDownList ddlUser;
        protected global::System.Web.UI.WebControls.DropDownList ddlDataType;
        protected global::System.Web.UI.WebControls.DropDownList ddlAccessType;
        protected global::System.Web.UI.WebControls.TextBox txtFromDate;
        protected global::System.Web.UI.WebControls.TextBox txtToDate;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.GridView gvAccessLog;
    }
}
