//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendance.WebForms
{
    public partial class EmployeeSelfService
    {
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Label lblVersion;
        protected global::System.Web.UI.WebControls.LinkButton btnHome;
        protected global::System.Web.UI.WebControls.LinkButton btnProfile;
        protected global::System.Web.UI.WebControls.LinkButton btnPayslip;
        protected global::System.Web.UI.WebControls.LinkButton btnDocuments;
        protected global::System.Web.UI.WebControls.LinkButton btnSettings;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblEmployeeName;
        protected global::System.Web.UI.WebControls.Label lblEmployeeID;
        protected global::System.Web.UI.WebControls.Label lblDepartment;
        protected global::System.Web.UI.WebControls.Label lblTodayStatus;
        protected global::System.Web.UI.WebControls.Label lblLeaveBalance;
        protected global::System.Web.UI.WebControls.Label lblMonthHours;
        protected global::System.Web.UI.WebControls.Label lblPendingApprovals;
        protected global::System.Web.UI.WebControls.LinkButton lnkProfile;
        protected global::System.Web.UI.WebControls.LinkButton lnkPayslip;
        protected global::System.Web.UI.WebControls.LinkButton lnkDocuments;
        protected global::System.Web.UI.WebControls.LinkButton lnkPassword;
        protected global::System.Web.UI.WebControls.LinkButton lnkContact;
        protected global::System.Web.UI.WebControls.LinkButton lnkBenefits;
        protected global::System.Web.UI.WebControls.Label lblEmpID;
        protected global::System.Web.UI.WebControls.Label lblFullName;
        protected global::System.Web.UI.WebControls.Label lblDeptName;
        protected global::System.Web.UI.WebControls.Label lblPosition;
        protected global::System.Web.UI.WebControls.Label lblEmail;
        protected global::System.Web.UI.WebControls.Label lblPhone;
        protected global::System.Web.UI.WebControls.Label lblStartDate;
        protected global::System.Web.UI.WebControls.Label lblManager;
        protected global::System.Web.UI.WebControls.GridView gvRecentActivity;
    }
}
