//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendance.WebForms
{
    public partial class EmployeeSettings
    {
        protected global::System.Web.UI.WebControls.LinkButton btnLogout; // ERROR: System.Web.UI.WebControls is not available in .NET 8.0. ASP.NET Web Forms is not supported in .NET Core/.NET 5+.
        protected global::System.Web.UI.WebControls.LinkButton btnHome;
        protected global::System.Web.UI.WebControls.LinkButton btnProfile;
        protected global::System.Web.UI.WebControls.LinkButton btnPayslip;
        protected global::System.Web.UI.WebControls.LinkButton btnDocuments;
        protected global::System.Web.UI.WebControls.LinkButton btnSettings;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.Button btnChangePassword;
        protected global::System.Web.UI.WebControls.CheckBox chkEmailNotifications;
        protected global::System.Web.UI.WebControls.CheckBox chkAttendanceAlerts;
        protected global::System.Web.UI.WebControls.CheckBox chkPayslipNotification;
        protected global::System.Web.UI.WebControls.CheckBox chkLeaveNotification;
        protected global::System.Web.UI.WebControls.Button btnSaveNotifications;
        protected global::System.Web.UI.WebControls.CheckBox chkTwoFactor;
        protected global::System.Web.UI.WebControls.Button btnEnableTwoFactor;
        protected global::System.Web.UI.WebControls.CheckBox chkProfileVisibility;
        protected global::System.Web.UI.WebControls.CheckBox chkDirectoryListing;
        protected global::System.Web.UI.WebControls.Button btnSavePrivacy;
        protected global::System.Web.UI.WebControls.Button btnDownloadData;
    }
}
