//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttendance.WebForms
{
    public partial class EmployeeDocuments
    {
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.LinkButton btnHome;
        protected global::System.Web.UI.WebControls.LinkButton btnProfile;
        protected global::System.Web.UI.WebControls.LinkButton btnPayslip;
        protected global::System.Web.UI.WebControls.LinkButton btnDocuments;
        protected global::System.Web.UI.WebControls.LinkButton btnSettings;
        protected global::System.Web.UI.WebControls.PlaceHolder phImportantDocs;
        protected global::System.Web.UI.WebControls.PlaceHolder phHRDocs;
        protected global::System.Web.UI.WebControls.PlaceHolder phBenefitsDocs;
        protected global::System.Web.UI.WebControls.PlaceHolder phTrainingDocs;
    }
}
