//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOHmiddleware.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQL5088.site4now.net;Initial Catalog=db_a8935f_slr;User Id=db_a8935f_" +
            "slr_admin;Password=0925Greg#")]
        public string SQLCon {
            get {
                return ((string)(this["SQLCon"]));
            }
            set {
                this["SQLCon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=C:\\Users\\Greg Adler\\SQLdb\\localbuffer.db;Version=3;")]
        public string LocalSQLiteCon {
            get {
                return ((string)(this["LocalSQLiteCon"]));
            }
            set {
                this["LocalSQLiteCon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SyncIntervalMinutes {
            get {
                return ((int)(this["SyncIntervalMinutes"]));
            }
            set {
                this["SyncIntervalMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DBN001")]
        public string SiteID {
            get {
                return ((string)(this["SiteID"]));
            }
            set {
                this["SiteID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQL5088.site4now.net;Initial Catalog=db_a8935f_slr;User Id=db_a8935f_" +
            "slr_admin;Password=0925Greg#")]
        public string SQLmyASP {
            get {
                return ((string)(this["SQLmyASP"]));
            }
            set {
                this["SQLmyASP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ICONNECTIVITY\\SQLEXPRESS;Initial Catalog=SOHdb;Integrated Security=Tr" +
            "ue")]
        public string SQLBackUp {
            get {
                return ((string)(this["SQLBackUp"]));
            }
            set {
                this["SQLBackUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2026")]
        public int AdminPass {
            get {
                return ((int)(this["AdminPass"]));
            }
            set {
                this["AdminPass"] = value;
            }
        }
    }
}
